### ISSUE TITLE
Update guest profile data for age

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/host-home-poc#37]
### Overview
Update the dummy date so that all guests are between ages 18 and 24. 

### Action Items

- [ ] Generate new age data for guest profiles so that all guests are between ages 18 and 24, inclusive

**Comment by c-fuchs** [comment]
@KarlenS this is what you mentioned to me at the meeting tonight, that we used the same data generation for guests and hosts so they have the same age ranges too. 

I don't want to assign it to you while you have more important things to do, but we should complete this before showing this to the client.

**Comment by KarlenS** [comment]
Sounds good! Yup, should definitely happen before the client sees the site.

To clarify, I meant just the age generation was the same for host/guest (by mistake). The data generation for hosts/guests is customized for each based on the questions in their respective application forms. The age "bug" is already fixed in the code and will be fixed in the next iteration of the data I get to Tyler.

**Comment by ExperimentsInHonesty** [comment]
age is 25.
